### ISSUE TITLE
custom warning message support

### ISSUE THREAD

**Issue by azu** [textlint-rule/textlint-rule-prh#5]
``` yml
  - expected: TechBooster
    pattern: tech
    prh: custom warning message
```

[prh](https://github.com/vvakame/prh) support `prh` field.
it is used for custom warning message.
